name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (curl, wget, libssl1.1)
      run: |
        apt-get update
        apt-get install curl wget libssl1.1 -y
    
    - name: Install Java for Embold Scanner
      run: |
        apt-get install openjdk-11-jre -y
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.0.x
        
    - name: Embold Analyse
      run: |
        # Download and extract the scanner
        curl ${{ vars.EMBOLD_SCANNER_URL}} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        
        # Download repository configuration
        curl --silent --location --request GET "${{ vars.EMBOLD_URL_CS}}/api/v1/repositories/0bf73c572ba3074f5a22f66b6a859233/scans/config/download" \
          --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" \
          -o repository-configuration.json
        echo "Download repository configuration file done"
        
        # Run the Embold Scanner
        ./browserstack-codequality-scanner/bin/embold-scanner analyse \
          -u ${{ vars.EMBOLD_URL_CS}} \
          -t ${{ secrets.EMBOLD_TOKEN_CS}} \
          -r 0bf73c572ba3074f5a22f66b6a859233 \
          -b . \
          -d ./embold-data \
          -c ./repository-configuration.json \
          -v

    - name: Archive logs and binaries
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: parsed_files
        path: |
          /__w/DevToys/DevToys/embold-data/**/*.txt
